// Copyright (C) 2026 Check Point Software Technologies Ltd. All rights reserved.

// Licensed under the Apache License, Version 2.0 (the "License");
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package policy

import (
	"bytes"
	"fmt"
	"math"
	"sort"
	"sync"

	"gopkg.in/yaml.v3"
)

// Renderer turns the canonical document into an artefact an agent consumes.
//
// Only LocalPolicyYAML exists today: in hybrid mode the agent compiles the
// declarative document itself. A fog-emulating manager would add a second
// implementation emitting the already-compiled policy.json that
// components/security_apps/local_policy_mgmt_gen/policy_maker_utils.cc:35-46
// produces, over this same model.
type Renderer interface {
	Name() string
	Render(doc Document) ([]byte, error)
}

// LocalPolicyYAML renders /etc/cp/conf/local_policy.yaml.
type LocalPolicyYAML struct{}

func (LocalPolicyYAML) Name() string { return "local_policy.yaml" }

const renderHeader = `# open-appsec declarative configuration
# Generated by open-appsec Manager. Edits made here are overwritten on the
# next apply; change the policy in the manager UI instead.
# Schema version: v1beta2 -- https://docs.openappsec.io
`

func (LocalPolicyYAML) Render(doc Document) ([]byte, error) {
	prepared, err := prepareForAgent(doc)
	if err != nil {
		return nil, err
	}

	order, err := schemaOrder()
	if err != nil {
		return nil, err
	}

	node, err := toOrderedNode(map[string]any(prepared), order)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	buf.WriteString(renderHeader)

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(node); err != nil {
		return nil, fmt.Errorf("encode policy yaml: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// prepareForAgent applies the corrections that make a document the agent will
// actually honour, rather than one it silently half-ignores.
func prepareForAgent(doc Document) (Document, error) {
	out, err := doc.Clone()
	if err != nil {
		return nil, err
	}

	// The agent's NewParsedRule reads `customResponse` (singular). A document
	// carrying the plural — as the shipped default policy does — would have
	// its custom response dropped, so fold it into the singular form here.
	// Validation has already warned about it.
	fixRule := func(rule map[string]any) {
		plural, has := rule["customResponses"]
		if !has {
			return
		}
		delete(rule, "customResponses")
		if _, hasSingular := rule["customResponse"]; !hasSingular {
			if s, ok := plural.(string); ok && s != "" {
				rule["customResponse"] = s
			}
		}
	}

	policies, _ := out["policies"].(map[string]any)
	if policies != nil {
		if def, ok := policies["default"].(map[string]any); ok {
			fixRule(def)
		}
		if rules, ok := policies["specificRules"].([]any); ok {
			for _, r := range rules {
				if rule, ok := r.(map[string]any); ok {
					fixRule(rule)
				}
			}
		}
	}
	return out, nil
}

// ---------------------------------------------------------- key ordering

// orderNode mirrors the schema's structure so rendering can emit keys in the
// order the schema declares them, rather than alphabetically. A policy file is
// something operators read and diff, so a stable, meaningful order matters.
type orderNode struct {
	keys  []string
	props map[string]*orderNode
	items *orderNode
}

var (
	orderOnce sync.Once
	orderRoot *orderNode
	orderErr  error
)

func schemaOrder() (*orderNode, error) {
	orderOnce.Do(func() {
		raw, err := schemaFS.ReadFile("schema/schema_v1beta2.yaml")
		if err != nil {
			orderErr = err
			return
		}
		var doc yaml.Node
		if err := yaml.Unmarshal(raw, &doc); err != nil {
			orderErr = err
			return
		}
		if len(doc.Content) == 0 {
			orderErr = fmt.Errorf("empty schema document")
			return
		}
		orderRoot = buildOrder(doc.Content[0])
	})
	return orderRoot, orderErr
}

// buildOrder walks a JSON Schema node, recording the declaration order of
// `properties` and descending through `items`.
func buildOrder(n *yaml.Node) *orderNode {
	if n == nil || n.Kind != yaml.MappingNode {
		return nil
	}
	out := &orderNode{props: map[string]*orderNode{}}

	for i := 0; i+1 < len(n.Content); i += 2 {
		key := n.Content[i].Value
		val := n.Content[i+1]

		switch key {
		case "properties":
			if val.Kind != yaml.MappingNode {
				continue
			}
			for j := 0; j+1 < len(val.Content); j += 2 {
				name := val.Content[j].Value
				out.keys = append(out.keys, name)
				if child := buildOrder(val.Content[j+1]); child != nil {
					out.props[name] = child
				}
			}
		case "items":
			out.items = buildOrder(val)
		}
	}
	return out
}

// toOrderedNode converts a value into a yaml.Node tree, ordering mapping keys
// by the schema where one applies and alphabetically otherwise. Alphabetical
// is the fallback rather than Go's map order so that output is deterministic.
func toOrderedNode(v any, order *orderNode) (*yaml.Node, error) {
	switch t := v.(type) {
	case map[string]any:
		node := &yaml.Node{Kind: yaml.MappingNode}
		for _, key := range orderedKeys(t, order) {
			var childOrder *orderNode
			if order != nil {
				childOrder = order.props[key]
			}
			valNode, err := toOrderedNode(t[key], childOrder)
			if err != nil {
				return nil, err
			}
			node.Content = append(node.Content,
				&yaml.Node{Kind: yaml.ScalarNode, Value: key, Tag: "!!str"},
				valNode)
		}
		return node, nil

	case []any:
		node := &yaml.Node{Kind: yaml.SequenceNode}
		var itemOrder *orderNode
		if order != nil {
			itemOrder = order.items
		}
		for _, item := range t {
			child, err := toOrderedNode(item, itemOrder)
			if err != nil {
				return nil, err
			}
			node.Content = append(node.Content, child)
		}
		// An empty sequence must render as `[]`, not as a blank value, or the
		// agent's yq conversion produces null where it expects a list.
		if len(t) == 0 {
			node.Style = yaml.FlowStyle
		}
		return node, nil

	default:
		node := &yaml.Node{}
		if err := node.Encode(normalizeNumber(t)); err != nil {
			return nil, err
		}
		return node, nil
	}
}

func orderedKeys(m map[string]any, order *orderNode) []string {
	seen := make(map[string]bool, len(m))
	keys := make([]string, 0, len(m))

	if order != nil {
		for _, k := range order.keys {
			if _, ok := m[k]; ok {
				keys = append(keys, k)
				seen[k] = true
			}
		}
	}

	rest := make([]string, 0, len(m))
	for k := range m {
		if !seen[k] {
			rest = append(rest, k)
		}
	}
	sort.Strings(rest)
	return append(keys, rest...)
}

// normalizeNumber renders whole-valued floats as integers.
//
// This is not cosmetic. Every policy makes a round trip through JSONB, which
// decodes all JSON numbers as float64, and yaml.v3 encodes a large float64 in
// scientific notation: maxBodySizeKb, whose schema default is 1000000, would
// be written as `1e+06`. The agent converts the YAML with `yq eval -o json`
// and parses the result into integer fields, so a value in that form breaks
// the load — and a failed policy load surfaces only at debug level
// (declarative_policy_utils.cc:115-118), making it very hard to diagnose.
func normalizeNumber(v any) any {
	f, ok := v.(float64)
	if !ok {
		return v
	}
	// Only convert values that are exactly integral and safely representable,
	// so genuine fractions such as a score of 9.5 are left alone.
	if f != math.Trunc(f) || math.Abs(f) > math.MaxInt64 {
		return v
	}
	return int64(f)
}
